config/routes.rb
# frozen_string_literal: true

TableGoExample::Application.routes.draw do
  root 'root#index'

  resources :books
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  belongs_to :publisher
end

app/models/publisher.rb
# frozen_string_literal: true

class Publisher < ApplicationRecord
  has_many :books, dependent: :nullify
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def pagination_defaults
    { per_page: 10, page: params[:page] }
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.paginate(pagination_defaults)

    respond_to do |format|
      format.html
      format.csv do
        send_data(render_to_string(template: 'books/index', format: :csv),
                  type: 'text/csv; charset=utf-8; header=present',
                  filename: 'books.csv',
                  disposition: 'attachment')
      end
    end
  end
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  def index
    @publishers = Publisher.all
    @authors = Author.includes(:books).paginate(pagination_defaults)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_controller?(*controllers)
    request.path[/^#{controllers.join('|')}/]
  end
end

app/views/books/_books.html.haml
= table_go_for @books, Book, :table_html => {:class => 'table table-striped table-hover table-bordered'} do |t|
  - t.column :title
  - t.column :isbn
  - t.column :pages
  - t.column :price, :as => :currency

app/views/books/index.csv.erb
<%= render 'books.html.haml' %>

app/views/books/index.html.haml
.page-header
  %h1
    table_go with download CSV link

.pull-right
  = will_paginate(@books)

= render 'books'

%p
  = link_to('Download as CSV', books_path(format: :csv), class: 'btn btn-primary')

%pre
  = "HAML:\n" + File.read(Rails.root + 'app/views/books/_books.html.haml')
  %br
  \= link_to('Download as CSV', books_path(format: :csv), class: 'btn btn-primary')


%pre
  = "Controller:\n" + File.read(Rails.root + 'app/controllers/books_controller.rb')

app/views/layouts/_footer.html.haml
%footer(style="margin: 20px")
  %hr
    © 2013 eXsemt

    .pull-right
      created by
      = link_to('eXsemt', 'http://exsemt.de/')

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57491005-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top.navbar-inverse(role="navigation")
  .container
    %navbar-header
      = link_to('TableGo Example', root_path, class: 'navbar-brand')
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li(class="#{'active' if current_controller?('/$')}")
          = link_to('Basic', root_path)
        %li(class="#{'active' if current_controller?('/books')}")
          = link_to('Download CSV example', books_path)

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %title
      TableGo Example
    %meta(http-equiv="Content-Type" content="text/html; charset=utf-8")
    %meta{ :name => 'run-env', :content => Rails.env }
    %meta{ name: "description", content: "This is example page for a 'table_go' gem with 'will_paginate' and 'bootstrap-sass'." }
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    - if content_for? :css
      = yield :css
    = javascript_include_tag "application", "data-turbolinks-track" => true
    - if content_for? :javascripts
      = yield :javascripts
    = csrf_meta_tags
    = render(partial: 'layouts/google_analytics.html.erb') if Rails.env.production?

  %body
    = render 'layouts/navigation'

    .container
      = yield

      = render 'layouts/footer'

app/views/root/_authors.html.erb
<div class="pull-right"><%= will_paginate(@authors) %></div>

<%= table_go_for @authors, Author, :table_html => {:class => 'table table-striped table-hover table-bordered'} do |t| %>
  <% t.column :first_name %>
  <% t.column :last_name  %>
<% end %>

app/views/root/_authors.html.haml
.pull-right
  = will_paginate(@authors)

= table_go_for @authors, Author, :table_html => {:class => 'table table-striped table-hover table-bordered'} do |t|
  - t.column :first_name
  - t.column :last_name

app/views/root/_authors_section.html.haml
.page-header
  %h1
    table_go with will_paginate
= render('authors.html.haml')

%pre
  = "HAML:\n" + File.read(Rails.root + 'app/views/root/_authors.html.haml')

%pre
  = "ERB:\n" + File.read(Rails.root + 'app/views/root/_authors.html.erb')

app/views/root/_publishers.html.erb
<div class="pull-right"><%= will_paginate(@publishers) %></div>

<%= table_go_for @publishers, Publisher, :table_html => {:class => 'table table-hover'} do |t| %>
  <% t.column :name %>
  <% t.column :place %>
<% end %>

app/views/root/_publishers.html.haml
= table_go_for @publishers, Publisher, :table_html => {:class => 'table table-hover'} do |t|
  - t.column :name
  - t.column :place

app/views/root/_publishers_section.html.haml
.page-header
  %h1
    Simple table with table_go
= render('publishers.html.haml')

%pre
  = "HAML:\n" + File.read(Rails.root + 'app/views/root/_publishers.html.haml')

%pre
  = "ERB:\n" + File.read(Rails.root + 'app/views/root/_publishers.html.erb')

app/views/root/index.html.haml
.jumbotron
  %p
    This is example page for a "table_go" gem with "will_paginate" and "bootstrap-sass".

= render('publishers_section')

= render('authors_section')